// Expo entry point for Android/iOS builds
// This file registers the main App component with Expo's runtime.
// It mirrors the default AppEntry generated by `expo init`.

import registerRootComponent from 'expo/build/launch/registerRootComponent';
import App from '../App';

// Register the main component. This is required for Metro bundler to locate the entry.
registerRootComponent(App);
